services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false
        bind:
            $mailer: '@app.mailer.transactional'

    AppBundle\VotingPlatform\:
        resource: ../../src/VotingPlatform/
