services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false
        bind:
            $mailer: '@app.mailer.transactional'
            $votingProcessWorkflow: '@state_machine.voting_process'

    App\VotingPlatform\:
        resource: ../../src/VotingPlatform/
