framework:
    cache:
        app: cache.adapter.doctrine
        default_doctrine_provider: cache.redis_doctrine_provider
        pools:
            app.cache.redirection:
                adapter: cache.adapter.doctrine
            app.cache.republican_silence: ~
