csa_guzzle:
    profiler: "%kernel.debug%"
    logger: true
    clients:
        mandrill_api:
            config:
                api_key: '%env(MANDRILL_API_KEY)%'
                base_uri: 'https://mandrillapp.com/api/1.0/'
                timeout: 10.0

        google_maps_static_api:
            config:
                base_uri: 'https://maps.googleapis.com'
                timeout: 2.0

        facebook_graph_api:
            config:
                base_uri: 'https://graph.facebook.com'
                timeout: 2.0

        mailchimp_api:
            config:
                base_uri: 'https://us16.api.mailchimp.com'
                timeout: 60.0
                headers:
                    User-Agent: 'En-Marche!'
                    Content-Type: 'application/json'
                    Authorization: 'Bearer %env(MAILCHIMP_API_KEY)%'

        dpt_api:
            config:
                base_uri: '%env(DPT_API_HOST)%'
                timeout: 15.0
