framework:
    secret:          "%env(APP_SECRET)%"
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    trusted_hosts:   ~
    session:
        name:        enmarche
        handler_id:  snc_redis.session.handler
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
