# This route must be loaded first to prevent another route to match his path
map_events:
    host:    "%app_host%"
    path:    /evenements/la-carte
    methods: GET
    defaults: { _controller: 'AppBundle\Controller\EnMarche\MapController:eventsAction' }
