controllers:
    resource: ../../src/Controller/
    type: annotation

#
# Health
#
app_health:
    host:     "%app_host%"
    resource: "../../src/Controller/HealthController.php"
    type:     "annotation"

#
# API
#
app_api:
    host:     "%app_host%"
    resource: "../../src/Controller/Api"
    type:     "annotation"
    prefix:   "%api_path_prefix%"
    defaults:
        _format: 'json'

#
# API Legislatives
#
app_legislatives_api:
    host:     "{app_domaines}"
    resource: "../../src/Controller/Api/LegislativesController.php"
    type:     "annotation"
    prefix:   "%api_path_prefix%"
    defaults:
        _format: 'json'
    requirements:
        app_domaines: "%app_host%|%legislatives_host%"

#
# OAuth
#
app_oauth:
    host:     "%app_host%"
    resource: "../../src/Controller/OAuth"
    type:     "annotation"
    prefix:   "/oauth/v2"

app_admin:
    host:     "%app_host%"
    resource: "../../src/Controller/Admin"
    type:     "annotation"
    prefix:   "/admin"

app_enmarche:
    host:     "%app_host%"
    resource: "../../src/Controller/EnMarche"
    type:     "annotation"

#
# AMP pages
#
app_enmarche_amp:
    host:     "%amp_host%"
    resource: "../../src/Controller/Amp"
    type:     "annotation"

#
# Legislatives app
#
app_legislatives:
    host:     "%legislatives_host%"
    resource: "../../src/Controller/Legislatives"
    type:     "annotation"
