swagger_ui:
    path: "%api_path_prefix%/swagger"
    controller: api_platform.swagger.action.ui

api_login_check:
    path: "%api_path_prefix%/login_check"

#
# En Marche app
#
lexik_paybox:
    host:     "%app_host%"
    resource: "@LexikPayboxBundle/Resources/config/routing.yml"
    prefix:   "/don"

react_citizen_projects:
    host:     "%app_host%"
    resource: "app.react_routing_loader:loadRoutes"
    type:     "service"

#
# Legacy
#
app_desintox:
    host: "%app_host%"
    path: /emmanuel-macron/desintox/{slug}
    defaults:
        slug: ~
        _controller: FrameworkBundle:Redirect:redirect
        route: ~

#
# Redirections
#
app_redirect_login:
    host: "%app_host%"
    path: /login
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: app_user_login

app_redirect_register:
    host: "%app_host%"
    path: /register
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: app_membership_join

app_redirect_inscription:
    host: "%app_host%"
    path: /inscription
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: app_membership_join
        permanent: true

# This route must be loaded the last to prevent an override
app_static_page:
    host:    "%app_host%"
    path:    /{slug}
    methods: GET
    defaults: { _controller: 'AppBundle\Controller\EnMarche\PageController:showPageAction' }
    requirements:
        slug: .+
