parameters:
    timeline_max_messages: 2

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    app.geocoder:
        class: 'Tests\App\Test\Geocoder\DummyGeocoder'
        public: false

    app.mailer.transactional_client:
        class: 'Tests\App\Test\Mailer\NullEmailClient'
        public: false

    app.mailer.campaign_client:
        class: 'Tests\App\Test\Mailer\NullEmailClient'
        public: false

    app.recaptcha.api_client:
        class: 'Tests\App\Test\Recaptcha\DummyRecaptchaApiClient'
        public: false

    Tests\App\Test\Algolia\DummySearchService:
        decorates: 'search.service'
        arguments: ['@Tests\App\Test\Algolia\DummySearchService.inner']

    data_collector.messenger:
        class: Symfony\Component\Messenger\DataCollector\MessengerDataCollector
        tags: [{ name: 'data_collector', id: messenger, template: profiler/messenger.html.twig }]

    App\VotingPlatform\Election\ResultCalculator:
        public: true
